// file_description: route generation logic for hazo_auth
// This module creates API route files in consuming projects

import * as fs from "fs";
import * as path from "path";

// section: types
type RouteDefinition = {
  name: string;
  path: string;
  method: string;
  export_name: string;
};

// section: constants
const ROUTES: RouteDefinition[] = [
  { name: "login", path: "api/hazo_auth/login", method: "POST", export_name: "loginPOST" },
  { name: "register", path: "api/hazo_auth/register", method: "POST", export_name: "registerPOST" },
  { name: "logout", path: "api/hazo_auth/logout", method: "POST", export_name: "logoutPOST" },
  { name: "me", path: "api/hazo_auth/me", method: "GET", export_name: "meGET" },
  { name: "forgot_password", path: "api/hazo_auth/forgot_password", method: "POST", export_name: "forgotPasswordPOST" },
  { name: "reset_password", path: "api/hazo_auth/reset_password", method: "POST", export_name: "resetPasswordPOST" },
  { name: "verify_email", path: "api/hazo_auth/verify_email", method: "GET", export_name: "verifyEmailGET" },
  { name: "resend_verification", path: "api/hazo_auth/resend_verification", method: "POST", export_name: "resendVerificationPOST" },
  { name: "update_user", path: "api/hazo_auth/update_user", method: "PATCH", export_name: "updateUserPATCH" },
  { name: "change_password", path: "api/hazo_auth/change_password", method: "POST", export_name: "changePasswordPOST" },
  { name: "upload_profile_picture", path: "api/hazo_auth/upload_profile_picture", method: "POST", export_name: "uploadProfilePicturePOST" },
  { name: "remove_profile_picture", path: "api/hazo_auth/remove_profile_picture", method: "DELETE", export_name: "removeProfilePictureDELETE" },
  { name: "library_photos", path: "api/hazo_auth/library_photos", method: "GET", export_name: "libraryPhotosGET" },
  { name: "get_auth", path: "api/hazo_auth/get_auth", method: "POST", export_name: "getAuthPOST" },
  { name: "validate_reset_token", path: "api/hazo_auth/validate_reset_token", method: "GET", export_name: "validateResetTokenGET" },
  { name: "profile_picture_filename", path: "api/hazo_auth/profile_picture/[filename]", method: "GET", export_name: "profilePictureFilenameGET" },
  { name: "invalidate_cache", path: "api/hazo_auth/invalidate_cache", method: "POST", export_name: "invalidateCachePOST" },
];

// section: helpers
function get_project_root(): string {
  return process.cwd();
}

function find_app_dir(project_root: string): string | null {
  const possible_dirs = [
    path.join(project_root, "app"),
    path.join(project_root, "src", "app"),
  ];

  for (const dir of possible_dirs) {
    if (fs.existsSync(dir)) {
      return dir;
    }
  }

  return null;
}

function ensure_dir(dir_path: string): void {
  if (!fs.existsSync(dir_path)) {
    fs.mkdirSync(dir_path, { recursive: true });
  }
}

function generate_route_content(route: RouteDefinition): string {
  return `// Generated by hazo_auth - do not edit manually
// Route: /${route.path}
// Method: ${route.method}
export { ${route.export_name} as ${route.method} } from "hazo_auth/server/routes";
`;
}

function file_exists(filepath: string): boolean {
  return fs.existsSync(filepath);
}

// section: main
export function generate_routes(custom_app_dir?: string): void {
  const project_root = get_project_root();
  
  console.log("\n\x1b[1m🐸 hazo_auth Route Generator\x1b[0m");
  console.log("=".repeat(50));
  console.log(`Project root: ${project_root}\n`);

  let app_dir = custom_app_dir 
    ? path.join(project_root, custom_app_dir)
    : find_app_dir(project_root);

  if (!app_dir) {
    console.error("\x1b[31mError: Could not find app directory.\x1b[0m");
    console.log("Try specifying it with: npx hazo_auth generate-routes --dir=src/app");
    process.exit(1);
  }

  if (!fs.existsSync(app_dir)) {
    console.error(`\x1b[31mError: App directory not found: ${app_dir}\x1b[0m`);
    process.exit(1);
  }

  console.log(`App directory: ${app_dir.replace(project_root, ".")}\n`);

  let created = 0;
  let skipped = 0;
  let errors = 0;

  console.log("\x1b[1mGenerating routes...\x1b[0m\n");

  for (const route of ROUTES) {
    const route_dir = path.join(app_dir, route.path);
    const route_file = path.join(route_dir, "route.ts");

    if (file_exists(route_file)) {
      console.log(`\x1b[33m[SKIP]\x1b[0m ${route.path}/route.ts (already exists)`);
      skipped++;
      continue;
    }

    try {
      ensure_dir(route_dir);

      const content = generate_route_content(route);
      fs.writeFileSync(route_file, content, "utf-8");

      console.log(`\x1b[32m[CREATE]\x1b[0m ${route.path}/route.ts`);
      created++;
    } catch (err) {
      console.log(`\x1b[31m[ERROR]\x1b[0m ${route.path}/route.ts - ${err instanceof Error ? err.message : "Unknown error"}`);
      errors++;
    }
  }

  console.log("\n" + "=".repeat(50));
  console.log("\x1b[1mSummary:\x1b[0m");
  console.log(`  \x1b[32m✓ Created: ${created}\x1b[0m`);
  console.log(`  \x1b[33m⊘ Skipped: ${skipped}\x1b[0m`);
  if (errors > 0) {
    console.log(`  \x1b[31m✗ Errors:  ${errors}\x1b[0m`);
  }
  console.log();

  if (created > 0) {
    console.log("\x1b[32m🦊 Routes generated successfully!\x1b[0m");
    console.log("\nNext steps:");
    console.log("  1. Run `npm run dev` to start your development server");
    console.log("  2. Test the routes with `curl http://localhost:3000/api/hazo_auth/me`");
    console.log("  3. Visit http://localhost:3000/api/hazo_auth/health to check setup status\n");
  } else if (skipped === ROUTES.length) {
    console.log("\x1b[33m🦊 All routes already exist. No changes made.\x1b[0m\n");
  }
}

